language: bash

env:
- TRAVIS_GLOBAL_WTF=1 # See https://github.com/docker/swarm/blob/master/.travis.yml
- _CONFIG=.config-3.17-std
- _CONFIG=.config-3.18-std

install:
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     curl -sLo - https://github.com/moul/travis-docker/raw/master/install.sh | sh -xe;
  fi

script:
- if [ "$TRAVIS_GLOBAL_WTF" ]; then
     for file in .config-*; do bash -n $file; done;
     for file in *.bash; do bash -n $file; done;
     make -n;
  fi
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     ./run make oldconfig;
  fi
