language: bash


sudo: false


env:
- TRAVIS_GLOBAL_WTF=1 # See https://github.com/docker/swarm/blob/master/.travis.yml
- _KERNEL=3.17.7-std
- _KERNEL=3.17.8-std
- _KERNEL=3.18.4-std
- _KERNEL=3.18.5-std
- _KERNEL=3.2.34-std


install:
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_prepare;
  fi


script:
- if [ "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_common;
  fi
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_kernel KERNEL=${_KERNEL};
  fi
