language: bash


sudo: false


env:
- TRAVIS_GLOBAL_WTF=1 # See https://github.com/docker/swarm/blob/master/.travis.yml
- _KERNEL=3.18.20-std
- _KERNEL=3.19.8-pbox
- _KERNEL=3.2.34-san
- _KERNEL=3.2.34-std
- _KERNEL=4.0.9-apparmor
- _KERNEL=4.0.9-docker
- _KERNEL=4.0.9-fedora
- _KERNEL=4.0.9-std
- _KERNEL=4.0.9-debug
- _KERNEL=4.1.2-std


install:
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_prepare;
  fi


script:
- if [ "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_common;
  fi
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_kernel KERNEL=${_KERNEL};
  fi
