language: bash


env:
- TRAVIS_GLOBAL_WTF=1 # See https://github.com/docker/swarm/blob/master/.travis.yml
- _KERNEL=3.2.34-std
#- _KERNEL=3.14-std
- _KERNEL=3.17-std
- _KERNEL=3.17-aufs
- _KERNEL=3.18-std
- _KERNEL=3.18-aufs
#- _KERNEL=3.18-xen


install:
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_prepare
  fi


script:
- if [ "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_common;
  fi
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_kernel KERNEL=${_KERNEL};
  fi
