language: bash


sudo: false


env:
- TRAVIS_GLOBAL_WTF=1 # See https://github.com/docker/swarm/blob/master/.travis.yml
- _KERNEL=3.18.16-std
- _KERNEL=3.19.8-pbox
- _KERNEL=3.2.34-san
- _KERNEL=3.2.34-std
- _KERNEL=4.0.7-apparmor
- _KERNEL=4.0.7-docker
- _KERNEL=4.0.7-fedora
- _KERNEL=4.0.7-std


install:
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_prepare;
  fi


script:
- if [ "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_common;
  fi
- if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
     make travis_kernel KERNEL=${_KERNEL};
  fi
