language: bash

services:
- docker

sudo: required

env:
- ACTION=check
- ACTION=build TRAVIS_TAG=4.1.6-std-1
- ACTION=build

before_install:
- docker images
- if [ "$ACTION" = "build" -a -n "$TRAVIS_TAG" ]; then docker pull moul/kernel-builder:stable-cross-armhf; fi
- docker images

script:
- env
- docker version
- docker info
- df -h
- if [ "$ACTION" = "check" ]; then make travis_check; fi
- if [ "$ACTION" = "build" -a -n "$TRAVIS_TAG" ]; then make travis_build; fi
- if [ -d dist ]; then ls -laR dist; fi
- docker info
- docker images
- df -h
